// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw7dSYMIuL5KvBBjvlvC_RtK9OtHw8C6U',
    appId: '1:649638830054:android:62695d2263bae78ba10027',
    messagingSenderId: '649638830054',
    projectId: 'tasko-9d2f5',
    storageBucket: 'tasko-9d2f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXnF8-vWa5n4m4y_CiEsFHdB_YUCULKD0',
    appId: '1:649638830054:ios:ae1046c33d2c2463a10027',
    messagingSenderId: '649638830054',
    projectId: 'tasko-9d2f5',
    storageBucket: 'tasko-9d2f5.appspot.com',
    androidClientId: '649638830054-c7j8lu61tv836hkm9tcgdkp8k6ts8to3.apps.googleusercontent.com',
    iosClientId: '649638830054-fo5nvffl4kjrtg904ss7tiu80qvduc9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasko',
  );
}
